---
sudo: required

services:
  - docker

language: minimal

before_install:
  - if [ "$TRAVIS_BRANCH" != "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      git checkout $TRAVIS_BRANCH;
    fi

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      ./scripts/docker_push.sh;
    fi
