FROM node:14.15.1 as builder

WORKDIR /website

COPY . /website

RUN npm install

ENV NODE_ENV live

ENV EN_SITE "https://\${EN_HOST}/"
ENV CY_SITE "https://\${CY_HOST}/"

COPY ./entrypoint.sh /website/nginx/entrypoint.sh
COPY ./nginx.conf /website/nginx/default.conf.template
