resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: craft-content-updated
    type: gcs-resource
    source:
      bucket: census-int-craft-craftcms
      json_key: ((gcp.service_account_json))
      versioned_file: meta/lastupdated.json

  - name: census-website-generator
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      private_key: ((github.census-website-generator))

  - name: census-website-generator-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website-generator
      username: _json_key
      password: ((gcp.service_account_json))

  - name: census-website-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website
      username: _json_key
      password: ((gcp.service_account_json))


jobs:

  - name: build-generator
    plan:
    - get: census-website-generator
      trigger: true
    - put: census-website-generator-docker-image
      params:
        build: census-website-generator
        dockerfile: census-website-generator/Dockerfile.generator
        build_args:
           CONTENT_SOURCE: https://storage.googleapis.com/census-int-craft-craftcms

      get_params:
        skip_download: true

  - name: build-website
    plan:
    - get: craft-content-updated
      trigger: true
      
    - get: census-website-generator-docker-image
      trigger: true
      passed:
        - build-generator
    - task: copy
      config:
        outputs:
          - name: docker-build
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sh
          args:
            - "-exc"
            - |
              cat >docker-build/Dockerfile <<EOL
              FROM eu.gcr.io/census-int-ci/website-generator as builder

              ENV CONTENT_SOURCE https://storage.googleapis.com/census-int-craft-craftcms

              RUN npm run generate-site

              FROM nginx

              COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
              COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
              COPY --from=builder /website/dist /usr/share/nginx/html

              ENV EN_HOST localhost-en
              ENV CY_HOST localhost-cy
              
              ENTRYPOINT ["/etc/entrypoint.sh"]
              EOL
    - put: census-website-docker-image
      params:
        build: docker-build
      get_params:
        skip_download: true
