resource_types:

  - name: file-url
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/concourse-url-resource

resources:
  - name: craft-entries-lastupdated-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries.json
      filename: entries-lastupdated.json

  - name: assets-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/assets.json
      filename: assets.json

  - name: entries-en-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-en.json
      filename: entries-en.json

  - name: entries-cy-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-cy.json
      filename: entries-cy.json

  - name: entries-ni-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-ni.json
      filename: entries-ni.json

  - name: globals-en-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-en.json
      filename: globals-en.json

  - name: globals-cy-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-cy.json
      filename: globals-cy.json

  - name: globals-ni-live
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-ni.json
      filename: globals-ni.json

  - name: craft-entries-lastupdated-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries.json?status=draft
      filename: entries-lastupdated.json

  - name: assets-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/assets.json?status=draft
      filename: assets.json

  - name: entries-en-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-en.json?status=draft
      filename: entries-en.json

  - name: entries-cy-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-cy.json?status=draft
      filename: entries-cy.json

  - name: entries-ni-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-ni.json?status=draft
      filename: entries-ni.json

  - name: globals-en-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-en.json?status=draft
      filename: globals-en.json

  - name: globals-cy-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-cy.json?status=draft
      filename: globals-cy.json
      
  - name: globals-ni-preview
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-ni.json?status=draft
      filename: globals-ni.json

  - name: census-website-generator
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      private_key: ((github.census-website-generator))
      branch: dev

  - name: census-website-generator-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website-generator-sandbox
      username: _json_key
      password: ((gcp.service_account_json))

  - name: census-website-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website-sandbox
      username: _json_key
      password: ((gcp.service_account_json))

  - name: census-website-docker-preview-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website-sandbox-preview
      username: _json_key
      password: ((gcp.service_account_json))


jobs:
  - name: build-generator
    plan:
    - get: census-website-generator
      trigger: true
    - put: census-website-generator-docker-image
      params:
        build: census-website-generator
        dockerfile: census-website-generator/Dockerfile.generator
      get_params:
        skip_download: true
        
  - name: build-sandbox-website
    plan:
      - get: craft-entries-lastupdated-live
        trigger: true
      - get: assets-live
      - get: entries-en-live
      - get: entries-cy-live
      - get: entries-ni-live
      - get: globals-en-live
      - get: globals-cy-live
      - get: globals-ni-live
      - task: fetch
        config:
          inputs:
            - name: assets-live
            - name: entries-en-live
            - name: entries-cy-live
            - name: entries-ni-live
            - name: globals-en-live
            - name: globals-cy-live
            - name: globals-ni-live
          outputs:
            - name: collated-data
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: google/cloud-sdk
          params:
            SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
          run:
            path: sh
            args:
              - "-exc"
              - |
                mkdir collated-data/data
                mkdir collated-data/assets
                cat >~/gcloud-service-key.json <<EOL
                  $SERVICE_ACCOUNT_JSON
                EOL
                gcloud auth activate-service-account --key-file ~/gcloud-service-key.json

                gsutil -m rsync -r gs://census-int-craft-sandbox-craftcms/assets collated-data/assets

                cp assets-live/assets.json collated-data/data
                cp entries-en-live/entries-en.json collated-data/data
                cp entries-cy-live/entries-cy.json collated-data/data
                cp entries-ni-live/entries-ni.json collated-data/data
                cp globals-en-live/globals-en.json collated-data/data
                cp globals-cy-live/globals-cy.json collated-data/data
                cp globals-ni-live/globals-ni.json collated-data/data

                ls -al collated-data/data
                ls -al collated-data/assets

      - task: build
        config:
          inputs:
            - name: collated-data
          outputs:
            - name: docker-build
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          run:
            path: sh
            dir: collated-data
            args:
              - "-exc"
              - |

                mkdir ../docker-build/content
                cp -R ./data ../docker-build/content
                cp -R ./assets ../docker-build/content

                cat >../docker-build/Dockerfile <<EOL

                FROM eu.gcr.io/census-int-ci/website-generator-sandbox as builder

                COPY content/ /tmp/content

                ENV ONS_STATIC_SITE_SOURCE /tmp/content

                RUN npm run generate-site

                FROM nginx

                COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
                COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
                COPY --from=builder /website/dist /usr/share/nginx/html

                ENV EN_HOST localhost-en
                ENV CY_HOST localhost-cy

                ENTRYPOINT ["/etc/entrypoint.sh"]
                EOL

      - put: census-website-docker-image
        params:
          build: docker-build
        get_params:
          skip_download: true

  - name: build-sandbox-preview-website
    plan:
      - get: craft-entries-lastupdated-preview
        trigger: true
      - get: assets-preview
      - get: entries-en-preview
      - get: entries-cy-preview
      - get: entries-ni-preview
      - get: globals-en-preview
      - get: globals-cy-preview
      - get: globals-ni-preview
      - task: fetch
        config:
          inputs:
            - name: assets-preview
            - name: entries-en-preview
            - name: entries-cy-preview
            - name: entries-ni-preview
            - name: globals-en-preview
            - name: globals-cy-preview
            - name: globals-ni-preview
          outputs:
            - name: collated-data
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: google/cloud-sdk
          params:
            SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
          run:
            path: sh
            args:
              - "-exc"
              - |
                mkdir collated-data/data
                mkdir collated-data/assets 
                cat >~/gcloud-service-key.json <<EOL
                  $SERVICE_ACCOUNT_JSON
                EOL
                gcloud auth activate-service-account --key-file ~/gcloud-service-key.json

                gsutil -m rsync -r gs://census-int-craft-sandbox-craftcms/assets collated-data/assets

                cp assets-preview/assets.json collated-data/data
                cp entries-en-preview/entries-en.json collated-data/data
                cp entries-cy-preview/entries-cy.json collated-data/data
                cp entries-ni-preview/entries-ni.json collated-data/data
                cp globals-en-preview/globals-en.json collated-data/data
                cp globals-cy-preview/globals-cy.json collated-data/data
                cp globals-ni-preview/globals-ni.json collated-data/data

      - task: build
        config:
          inputs:
            - name: collated-data
          outputs:
            - name: docker-build
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          run:
            path: sh
            dir: collated-data
            args:
              - "-exc"
              - |

                mkdir ../docker-build/content
                cp -R ./data ../docker-build/content
                cp -R ./assets ../docker-build/content

                cat >../docker-build/Dockerfile <<EOL

                FROM eu.gcr.io/census-int-ci/website-generator-sandbox as builder

                COPY content/ /tmp/content

                ENV ONS_STATIC_SITE_SOURCE /tmp/content

                RUN npm run generate-site

                FROM nginx

                COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
                COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
                COPY --from=builder /website/dist /usr/share/nginx/html

                ENV EN_HOST localhost-en
                ENV CY_HOST localhost-cy

                ENTRYPOINT ["/etc/entrypoint.sh"]
                EOL

      - put: census-website-docker-preview-image
        params:
          build: docker-build
        get_params:
          skip_download: true