resource_types:

  - name: file-url
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/concourse-url-resource

resources:
  - name: craft-entries-lastupdated
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries.json
      filename: entries-lastupdated.json

  - name: assets
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/assets.json
      filename: assets.json

  - name: entries-en
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-en.json
      filename: entries-en.json
  - name: entries-cy
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-cy.json
      filename: entries-cy.json
  - name: entries-ni
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/entries-ni.json
      filename: entries-ni.json
  - name: globals-en
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-en.json
      filename: globals-en.json
  - name: globals-cy
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-cy.json
      filename: globals-cy.json
  - name: globals-ni
    type: file-url
    source:
      url: https://api.craftcms-sandbox.int.census-gcp.onsdigital.uk/api/globals-ni.json
      filename: globals-ni.json

  - name: census-website-generator
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      private_key: ((github.census-website-generator))

  - name: census-website-generator-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website-generator-sandbox
      username: _json_key
      password: ((gcp.service_account_json))

  - name: census-website-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-int-ci/website-sandbox
      username: _json_key
      password: ((gcp.service_account_json))


jobs:
  - name: build-sandbox-website
    plan:
      - get: craft-entries-lastupdated
        trigger: true
      - get: assets
      - get: entries-en
      - get: entries-cy
      - get: entries-ni
      - get: globals-en
      - get: globals-cy
      - get: globals-ni
      - task: fetch
        config:
          inputs:
            - name: assets
            - name: entries-en
            - name: entries-cy
            - name: entries-ni
            - name: globals-en
            - name: globals-cy
            - name: globals-ni
          outputs:
            - name: collated-data
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: google/cloud-sdk
          params:
            SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
          run:
            path: sh
            args:
              - "-exc"
              - |
                mkdir collated-data/data
                mkdir collated-data/assets 

                cp assets/assets.json collated-data/data
                cp entries-en/entries-en.json collated-data/data
                cp entries-cy/entries-cy.json collated-data/data
                cp entries-ni/entries-ni.json collated-data/data
                cp globals-en/globals-en.json collated-data/data
                cp globals-cy/globals-cy.json collated-data/data
                cp globals-ni/globals-ni.json collated-data/data

      - task: build
        config:
          inputs:
            - name: collated-data
          outputs:
            - name: docker-build
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          run:
            path: sh
            dir: collated-data
            args:
              - "-exc"
              - |

                mkdir ../docker-build/content
                cp -R ./data ../docker-build/content
                cp -R ./assets ../docker-build/content

                cat >../docker-build/Dockerfile <<EOL

                FROM eu.gcr.io/census-gcr-cw/website-generator as builder

                COPY content/ /tmp/content

                ENV ONS_STATIC_SITE_SOURCE /tmp/content

                RUN npm run generate-site

                FROM nginx

                COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
                COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
                COPY --from=builder /website/dist /usr/share/nginx/html

                ENV EN_HOST localhost-en
                ENV CY_HOST localhost-cy

                ENTRYPOINT ["/etc/entrypoint.sh"]
                EOL

      - put: census-website-docker-image
        params:
          build: docker-build
        get_params:
          skip_download: true