resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

  - name: file-url
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/concourse-url-resource

resources:
  - name: pipelines
    type: concourse-pipeline
    source:
      target: http://concourse-web:8080/
      teams:
      - name: cw
        username: cw
        password: ((concourse.team-pass))

  - name: census-website-cms
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-cms.git
      private_key: ((github.census-website-cms))

  - name: census-website-generator
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      private_key: ((github.census-website-generator))

  - name: census-website-generator-pipelines
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      paths:
      - "pipelines"
      private_key: ((github.census-website-generator))
      
  - name: census-website-generator-concourse-url-resource
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      paths:
      - "docker-images/concourse-url-resource"
      private_key: ((github.census-website-generator))

  - name: census-website-generator-tags
    type: git
    source:
      uri: git@github.com:ONSdigital/census-website-generator.git
      private_key: ((github.census-website-generator))
      tag_filter: "*"

  - name: craft-cms-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/craftcms
      username: _json_key
      password: ((gcp.service_account_json))
      
  - name: concourse-url-resource-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/concourse-url-resource
      username: _json_key
      password: ((gcp.service_account_json))

  - name: census-website-generator-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/website-generator
      username: _json_key
      password: ((gcp.service_account_json))

  - name: census-website-docker-image
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/website
      username: _json_key
      password: ((gcp.service_account_json))
      
  - name: census-website-docker-image-prod
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/website
      tag: prod
      username: _json_key
      password: ((gcp.service_account_json))
  
  - name: census-website-docker-image-blacklodge
    type: docker-image
    source:
      repository: eu.gcr.io/census-gcr-cw/website
      tag: blacklodge
      username: _json_key
      password: ((gcp.service_account_json))

  - name: entries-lastupdated
    type: file-url
    source:
      url: http://craftcms/api/entries.json
      filename: entries-lastupdated.json

  - name: assets
    type: file-url
    source:
      url: http://craftcms/api/assets.json
      filename: assets.json

  - name: entries-en
    type: file-url
    source:
      url: http://craftcms/api/entries-en.json
      filename: entries-en.json
  - name: entries-cy
    type: file-url
    source:
      url: http://craftcms/api/entries-cy.json
      filename: entries-cy.json
  - name: entries-ni
    type: file-url
    source:
      url: http://craftcms/api/entries-ni.json
      filename: entries-ni.json
  - name: globals-en
    type: file-url
    source:
      url: http://craftcms/api/globals-en.json
      filename: globals-en.json
  - name: globals-cy
    type: file-url
    source:
      url: http://craftcms/api/globals-cy.json
      filename: globals-cy.json
  - name: globals-ni
    type: file-url
    source:
      url: http://craftcms/api/globals-ni.json
      filename: globals-ni.json
jobs:
  - name: fly-pipeline
    plan:
    - get: census-website-generator-pipelines
      trigger: true
    - put: pipelines
      params:
        pipelines:
        - name: website
          team: cw
          config_file: census-website-generator-pipelines/pipelines/website.yml

  - name: set-secrets
    plan:
      - task: set-secrets
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: 
              repository: gcr.io/cloud-builders/kubectl
          params:
            SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
          run:
            path: /bin/bash
            args:
              - -ce
              - |-
                cat >~/gcloud-service-key.json <<EOL
                $SERVICE_ACCOUNT_JSON
                EOL

                gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
                gcloud container clusters get-credentials k8s-cd --zone europe-west2 --project census-ci --internal-ip
                
                echo CiQAEsQp67SFQMIitaeydVELAy0PiCjX/D2AfTeSnCZQrDasfPQSuQ0AKGmNduJKBNCXpEJ80ENk1MpQsh+fBOSGSXfoW2fUL/jrQrd7YVh9OpDgB0x76Gh848cAvpnn6W2IBFuMCebMG8vULczUlsHMc/d1jUb3tqgMmYRrrni1p0B9TEdj9hmeEX2NVWaEraFJDMeRxJaMzDSpLaHGDiqZlWq3JqCpPhmqebDfO5qFEsTflp3f1Xz7WEDTuiYJnnadBkzecKcV/lGLlvT7R0GA44oyMTPLyhIlGwYVcVuKeIyMNil7t1wJHkSS0IU6ibKWUDYhbNWoVVAAIW9uDTHBz6Y/BeLPFn3IqaYESwZ2ffsx03i/B5IwmMqAj07Kl0Pxip0ogHiJI3tpZohS5BmazwimjhOmKtHF4EiAwIRWNQf19gvnAKt/NgPrXqG7EVh3CG1UTe5j6C2V7iNEd6LKxuC/omAbllvAVDbvT3xHY05D0f2EjppWq2yMzXGPKltJmmNfN5OxaLtBGHSDzSLPF1ocPMufwWSMXdJ/M04CmLvOg4kLD6k7vBpRwls/2hm3519NCL5Z6Vku1yftoMF64Wtl6+bRcDUpw3BZM9Fwemy+67jMgGcIPez7C0c6lZM+yigGaj0IxO0c5vLhrGNkf/b9Orc7Yp6qA+5746uDyPQUm+pyyzMfkI0Z+oUs+LbKPGEKVe68CDv2MDbVQCWIago8WA6a5e99IPTzZ6C5vCd4wYPuSHMqTFn8PH4qfFYGQ9/GSbsVlvjioC8psHmIHMATBPOIlsPpk2ivtP41cgaWlFgw2GllMdsADQYjIenHR4Nby8RccVI2ytd1HWwJXd0lMbDSbEEksE/jHBQf8e2rnkYu7a5Lger3EXxf0EebbU77KuKpXeQlW2aLqiWzHsqUryAYf8bmsol92WjVmU2WXCjA78sNiUYoa23ImOxzRuhfYFUaP2RMCyFYpQDp0acgNaJ807HYlq54CtVopAMfZy1+8CtspxwpoemD/6e7Ko4cH5q34VPM5NqwLdvzrlFKAQYJP67ySm6ZlnA6tlY1QEuTjgYyh0kZR2qqAH9Ugct57LU+1Hw1z5Z26BGj43+oreAGmsqRmgrUm32iP/v6vIDh8Ufh2Pv8l/XOXCCpylnGlPkWONoBO2t9knrkDlgSZ7amhkHOSpz9CRBgMoAoTbIYthNE9Rilb5NQJZdIJuEmrzd0AMqUkSW7/g4yw3uWLKv9CWcAwDfFj9NR78u7RdI7VxOCR9h/D4P1MSnoIG6cuMhi6ARjWC9xFa9kh1nRmk86tVgfJUR6l31THQvxpYFSzmXM7N2hltHro8lTZsJbcNtqw9FfER3G8lw68RVeS8H/xyduvSgeCe77ixDThwDOiR64PTB+Bh+Nexv+9DQljBCr+/1Mv8cyWm4qnEO7yFdtVnFuXdZVtFEHnzEuBvvw7kgMU2MBsQ8fP4kTIPYQNLVIrCvMXQjlEa7CNcOxM5/w3856eGQy0gHu5xowDPqHO9F4CwZ0AT7RgZ/GcGQQ1NM34heDaglJJUP2lPU+zrbngfsidwR5O7rxPzf55ZIhA+8VXQydyjNiPPIBPyM2sreEpYmIylw/9gMTJUj/QpaiepsTo8QFNHP5MONhWmZ+77s7qjvy2sqY2D0bAg/0oobXP5W6jZc2lmNAp6EkCZcp+tncc/TiKG8Vc/nu0zNdKIzalI/pMNjYWp+gh8LzU+5dnAsUHU6z68AqjriZcVUPs7KTpknjJwtKhAu/XL9SLoNpWX4M/QoV1BtocHOKNx1o4/N9/aX/Yi6SCrKa75EP623AdQ842Z4Vrt4zg+8AxzwlPikZhqz6MAtXB/cUzSj6nG5RLgDqYJHFgwDMpaZg+wJ1EH7i/+SFK0+3QA0YmXxwEe0G3kYbX3LO1oJW6G1EjNkiikf3qcncM4EJiVwCB1NPCa0hkhMmnZV/nvyPmEfVdSlpGz3rg4AMjun4aLsmtON0G8vWHava7SHQBGKpPESmp3cjAbQVKpmiuL1f7shpnBPZe2k1iB9bbRPOpF7GT3wefDs4+maWDkQQJISq7dKbmowyO94c1s/mpToFPWKQIANlhMcrXOd6CfKcDOUmwhOGux3ySu17H9EeyloEGT+QxlvPM5sx4/3xH7whGLLD5BddFpQXlQlBRsZtsqilRiwd8R35h7XT92e0qdrdaqe7v2V7LXR+GiYQl1Z/HW2eB2/yqTVBld+oorFAuuNxjxVD4M2B66vt6P58fYZvPhk+w8nX4WVS68VFjB00QArmglIS1flSndWe0OhvIwuOrRchRMZn525jvzpnstz3Er42sjHsQqvI4A== | base64 -d | gcloud kms decrypt --project census-ci --location europe-west2 --keyring concourse --key cw --plaintext-file census-website-cms --ciphertext-file -

                echo CiQAEsQp67x77zKm38Ll2s3ekffX6lhggw7eM1xfjpiMH8wP9S0StQ0AKGmNdsnmbCknMcw0QvAYc8pUo1keC/QBkjpDg8tY1JhNGr3zdOP422P4vSiO6Ju163zsrzh5RHUiy3zRglryFGoUnUOD0HTUWWGxA3sviHBi2UhBwr57xU5S+VhhJ7TTVmNGDoFxH3Eau1cHXV8/2og+iYYeDAKLP7QvKCYkSO0YJDD61fVhEAh+dlRBt36lweseNYjhNu6dLkxquw63j7EenBz46QbvqG65lS+lqWgJED510/ajge0rnSyFa+Gx2W0a2LeffTiAQjKMeAehnD/jpirbTuvnZKA4QtOrvLCiLjvL3D5seysHLnijzEbrkiI4sFnBS7egCrncquRdBkb6RcG8b3CwG3ONzWdw8wJ0eSH6Rj54unVTR77Ed7PFUxh/3e+Msh+G3/pwP9IXn5swW37HFpAQ1YN7E8y0Gtt6uQmSm/BvU9gXshsPFtrwBaPJTLVPFMMndXvlr2WogrRUiwzvSgqUinoL0MZdODcjj8GOqTROyjHoFwkWTI0lOXE4sQkjlFV+p1+Qh1fJUTxQl/Yg4/z4TawJeg68bSXvUkOeQUbDv7wuP6EVuB7VAcB2HeppnjRMNojRWM5N//8BNKKwSRS/gCYLb+rVhE6NY5MS0YI4R7ye34YG75BjcI3ZpG3E64Fh8u5PJI+Okew8M5KZ95byK/qYWTQAnvPXplhvwHSuHHV/vtyJIQWgDmhIVEbtFgOThWQKhAt9vmRNhTuWHUCBhljJngZAUg/jGeMPMKePpKxHJyrG1hCkyQHXcCkYL8/cvR/lVv0Bi7Q87pf8LWc+95T4gclUCmBjZMJ1qV4576GezT5vk5u4cMk/N6yf3KT8mT1PgW787dittMDxV0+Mvp76lpql5seyVTZ0nBNw2wYlYcKNmbXQlkDc0Y/JL5BIuibrFFHMYBXCkgo/hGDHD8l7LbiLgB1B3IikTKS5BsYLTQz+2onCi3gBjNsQnSiaRO78vNR5Y26ChWWVQzQ/bKeZxVAomWvs3Y1c2BK72bTF0kKhOEVLLO+zni5/kvtUvFSlIAGgjhvPwmV97iODboaJlpcKk899Nhu2snOKxGINaj0POTK6R8Bb3Pnoolu16XOC+DKfxhvCcnBbh+RvTt0+mF9HCSLym44cXTT+PQhMj8iwWRwL6Qn2v4QW4DxGlbtCS+OMsk7IutyHSszxVnJqWQcx/Wwii1ByJht3SKOBd/PyotrZ9SKiYyrlaH1urO6EGQI3Dm13YlRs+BSdsyG5PsSV5jBM1vpr/LlWjOy3JQGgiealD2WNOQ2mvAN1CG6b2fevH532TSzUMkUFCaCSaQQ64jFRKghQTdKEK79eRjgW0TagtR1HBt6dFMz/9hCbJW92wtS/OAPMslvUqksREWB7ru5t9Lv1tEJnfQHlvzaZJk+rg+PbcQGm2BBU/P3Ca5jmUZ4OSO86i+6cAKDn2S7EI70+iheVdZNZ5u2pfqWvlJw3nMP+5wnRV6Dyvy8E3We6Q9sgTpXPGJBptP3r/9zcQzgQfoz1SuV/GsTxTdykoeEMaMkUXPD3/PE3cetYEiDnwjBTduubx7y2y1bJ+5+A+LIpmGTDXjh0aZ0gtFxQ0Wm9UPWDZscwe6T1+9J6NwbRX2ot47dFXuiAPCUfnR02AfPaK8H/xVKnuGWmEeivzLDtjJ/fZJywGaTvJYpXdykv+epijisVPFwR2QIN1L7T9xwQ2UH5cSb0MvGTD2BpGamZGbX7w4NdccgJNnsjtxTLDatJkprVeSzQFwfQBtNzBMiUOpwTv5MHXFq9qYaXqnot2fR99q3tZALldEXvZq5lgS1yQB/Id7bxUL6akk4JWnmhqsDaLZ2eCFLSgYzeXp6ffM4GfdscQWPaKA9zqT8BGWI3/lFkqQ3L/uqKD9zMZDXElUD3yEJFHUH/AxlABohMK+NDiBeXDjVyQj4Su9cPdgjEH1YVkQUSvYAV8kGbf6f3afie/HLvm/4TMOT3IdAt4yB4YVCG+kPy9ueM1TsbTrbRbvC5b+LGyAvOVKocA6S7nzT/tuekrSP0AkRC3y9o856zp1KHS/YQgvKg2LKKQbo/bEDuqCrdb4gsYkNK9UAapTrhkRRL6Knn5uBEACQDYyQGXG3shYJQpXrc+//jTUv789zk2mmCaS7w4zfrS2iXHGVJXO+kisT7nBoKV8RN5jWc84GOU6RzEWecmrYPH/zW9erSGk+asaVwrfXRAnzmKyKD+svCRR1YoQRVnr2LTe0w4tvM4TvxbiYmFLPZ26dBIyzDJl+z6U4XEoEBdgPFkShE | base64 -d | gcloud kms decrypt --project census-ci --location europe-west2 --keyring concourse --key cw --plaintext-file census-website-generator --ciphertext-file -
                
                kubectl create secret generic github -n concourse-cw --from-file=census-website-cms --from-file=census-website-generator --dry-run -o yaml | kubectl apply -f -

  - name: build-craft
    plan:
    - get: census-website-cms
      trigger: true
    - put: craft-cms-docker-image
      params:
        build: census-website-cms
      get_params:
        skip_download: true

  - name: build-concourse-url-resource
    plan:
    - get: census-website-generator-concourse-url-resource
      trigger: true
    - put: concourse-url-resource-docker-image
      params:
        build: census-website-generator-concourse-url-resource/docker-images/concourse-url-resource
      get_params:
        skip_download: true

  - name: build-generator
    plan:
    - get: census-website-generator
      trigger: true
    - put: census-website-generator-docker-image
      params:
        build: census-website-generator
        dockerfile: census-website-generator/Dockerfile.generator
      get_params:
        skip_download: true
  - name: build-generator-release
    plan:
    - get: census-website-generator-tags
      trigger: true
    - put: census-website-generator-docker-image
      params:
        tag: census-website-generator-tags/.git/ref
        build: census-website-generator-tags
        dockerfile: census-website-generator-tags/Dockerfile.generator
      get_params:
        skip_download: true

  - name: copy-entries
    plan:
    - get: entries-lastupdated
      trigger: true
    - get: assets
    - get: entries-en
    - get: entries-cy
    - get: entries-ni
    - get: globals-en
    - get: globals-cy
    - get: globals-ni
    - task: copy
      config:
        inputs:
          - name: assets
          - name: entries-en
          - name: entries-cy
          - name: entries-ni
          - name: globals-en
          - name: globals-cy
          - name: globals-ni
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: google/cloud-sdk
        params:
          SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
        run:
          path: sh
          args:
            - "-exc"
            - |
              cat >~/gcloud-service-key.json <<EOL
              $SERVICE_ACCOUNT_JSON
              EOL

              gcloud auth activate-service-account --key-file ~/gcloud-service-key.json

              gsutil cp assets/assets.json entries-en/entries-en.json entries-cy/entries-cy.json entries-ni/entries-ni.json globals-en/globals-en.json globals-cy/globals-cy.json  globals-ni/globals-ni.json gs://census-ci-craftcms/

  - name: build-website
    plan:
    - get: entries-lastupdated
      trigger: true
      passed:
        - copy-entries
    - get: census-website-generator-docker-image
      trigger: true
      passed:
        - build-generator
    - task: copy
      config:
        outputs:
          - name: docker-build
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sh
          args:
            - "-exc"
            - |
              cat >docker-build/Dockerfile <<EOL
              FROM eu.gcr.io/census-gcr-cw/website-generator as builder
              RUN npm run generate-site

              FROM nginx

              COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
              COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
              COPY --from=builder /website/dist /usr/share/nginx/html

              ENV EN_HOST localhost-en
              ENV CY_HOST localhost-cy

              ENTRYPOINT ["/etc/entrypoint.sh"]
              EOL
    - put: census-website-docker-image
      params:
        build: docker-build
      get_params:
        skip_download: true

  - name: build-website-prod
    plan:
    - get: entries-lastupdated
      trigger: true
      passed:
        - copy-entries
    - task: copy
      config:
        outputs:
          - name: docker-build
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sh
          args:
            - "-exc"
            - |
              cat >docker-build/Dockerfile <<EOL
              FROM eu.gcr.io/census-gcr-cw/website-generator:v1.4.9 as builder
              RUN npm run generate-site

              FROM nginx

              COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
              COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
              COPY --from=builder /website/dist /usr/share/nginx/html

              ENV EN_HOST localhost-en
              ENV CY_HOST localhost-cy

              ENTRYPOINT ["/etc/entrypoint.sh"]
              EOL
    - put: census-website-docker-image-prod
      params:
        build: docker-build
      get_params:
        skip_download: true

  - name: build-website-blacklodge
    plan:
    - get: entries-lastupdated
      trigger: true
      passed:
        - copy-entries
    - task: copy
      config:
        outputs:
          - name: docker-build
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        run:
          path: sh
          args:
            - "-exc"
            - |
              cat >docker-build/Dockerfile <<EOL
              FROM eu.gcr.io/census-gcr-cw/website-generator:v1.4.10 as builder
              RUN npm run generate-site
              FROM nginx
              COPY --from=builder /website/nginx/entrypoint.sh /etc/entrypoint.sh
              COPY --from=builder /website/nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
              COPY --from=builder /website/dist /usr/share/nginx/html
              ENV EN_HOST localhost-en
              ENV CY_HOST localhost-cy
              ENTRYPOINT ["/etc/entrypoint.sh"]
              EOL
    - put: census-website-docker-image-blacklodge
      params:
        build: docker-build
      get_params:
        skip_download: true
